In [5]:
%cd "C:/Users/ajcltm/vscode/data/250811_ecoDataSystem"

C:\Users\ajcltm\vscode\data\250811_ecoDataSystem

c:\Users\ajcltm\vscode\data\250811_ecoDataSystem\.venv\lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [6]:
from etl_task.staging import staging_pickle

In [7]:
staged = staging_pickle.load_pickle("250818_193611 stockcorpfnltt.pkl")

In [9]:
import pandas as pd

valid_data = [d for d in staged if not "error" in d]
len(valid_data)

2753

In [19]:
valid_df = pd.DataFrame(valid_data)
valid_df.head()

,corp_code,fs_div,유동자산,비유동자산,자산총계,유동부채,비유동부채,부채총계,자본금,이익잉여금,...,예수부채,영업이익(손실),순이자손익,순수수료손익,파생상품부채,보험계약자산,보험계약부채,파생상품관련손익,금융상품관련순손익,금융부채
0,00126380,CFS,"227,062,266,000,000","287,469,682,000,000","514,531,948,000,000","93,326,299,000,000","19,013,579,000,000","112,339,878,000,000","897,514,000,000","370,513,188,000,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00164742,CFS,"115,764,287,000,000","224,034,142,000,000","339,798,429,000,000","79,509,643,000,000","140,012,853,000,000","219,522,496,000,000","1,488,993,000,000","96,595,668,000,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01170962,CFS,"2,491,420,979","6,390,292,498","8,881,713,477","906,519,109","3,098,990,529","4,005,509,638","770,089,223","3,127,328,074",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01139266,CFS,"4,737,704,248","359,005,973","5,096,710,221","3,740,962,515","84,366,490","3,825,329,005","1,003,707,845","249,716,773",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01107665,CFS,"1,539,117,621","1,066,578,097","2,605,695,718","123,828,000","47,255,285","171,083,285","432,706,627","1,417,630,122",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
valid_df.columns
view_columns = ['corp_code', 'fs_div', '유동자산', '비유동자산', '자산총계', '부채총계', '자본총계', '매출액', '영업이익', '당기순이익', '당기순이익(손실)']
vv_df = valid_df[view_columns]
vv_df.head()

,corp_code,fs_div,유동자산,비유동자산,자산총계,부채총계,자본총계,매출액,영업이익,당기순이익,당기순이익(손실)
0,00126380,CFS,"227,062,266,000,000","287,469,682,000,000","514,531,948,000,000","112,339,878,000,000","402,192,070,000,000","300,870,903,000,000","32,725,961,000,000","34,451,351,000,000","34,451,351,000,000"
1,00164742,CFS,"115,764,287,000,000","224,034,142,000,000","339,798,429,000,000","219,522,496,000,000","120,275,933,000,000","175,231,153,000,000","14,239,592,000,000","13,229,908,000,000","13,229,908,000,000"
2,01170962,CFS,"2,491,420,979","6,390,292,498","8,881,713,477","4,005,509,638","4,876,203,839","4,574,221,304","798,079,282","600,145,982","600,145,982"
3,01139266,CFS,"4,737,704,248","359,005,973","5,096,710,221","3,825,329,005","1,271,381,216","2,693,371,318","103,270,506","91,781,317","91,781,317"
4,01107665,CFS,"1,539,117,621","1,066,578,097","2,605,695,718","171,083,285","2,434,612,433","518,897,047","99,577,615","44,846,555","44,846,555"

In [21]:
vv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2753 entries, 0 to 2752
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   corp_code  2753 non-null   object
 1   fs_div     2753 non-null   object
 2   유동자산       2668 non-null   object
 3   비유동자산      2646 non-null   object
 4   자산총계       2753 non-null   object
 5   부채총계       2753 non-null   object
 6   자본총계       2753 non-null   object
 7   매출액        2633 non-null   object
 8   영업이익       2662 non-null   object
 9   당기순이익      2749 non-null   object
 10  당기순이익(손실)  2749 non-null   object
dtypes: object(11)
memory usage: 236.7+ KB

In [23]:
numeric_columns = ['유동자산', '비유동자산', '자산총계', '부채총계', '자본총계', '매출액', '영업이익', '당기순이익', '당기순이익(손실)']
vv_df.apply(lambda col: col.str.replace(',', '', regex=True) if col.name in numeric_columns else col).apply(lambda col: col.str.replace("-", "", regex=True) if col.name in numeric_columns else col).apply(pd.to_numeric, errors='coerce'  ).info()
vv_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2753 entries, 0 to 2752
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   corp_code  2753 non-null   int64
 1   fs_div     0 non-null      float64
 2   유동자산       2668 non-null   float64
 3   비유동자산      2645 non-null   float64
 4   자산총계       2752 non-null   float64
 5   부채총계       2753 non-null   int64
 6   자본총계       2753 non-null   int64
 7   매출액        2628 non-null   float64
 8   영업이익       2662 non-null   float64
 9   당기순이익      2749 non-null   float64
 10  당기순이익(손실)  2749 non-null   float64
dtypes: float64(8), int64(3)
memory usage: 236.7 KB

,corp_code,fs_div,유동자산,비유동자산,자산총계,부채총계,자본총계,매출액,영업이익,당기순이익,당기순이익(손실)
0,00126380,CFS,"227,062,266,000,000","287,469,682,000,000","514,531,948,000,000","112,339,878,000,000","402,192,070,000,000","300,870,903,000,000","32,725,961,000,000","34,451,351,000,000","34,451,351,000,000"
1,00164742,CFS,"115,764,287,000,000","224,034,142,000,000","339,798,429,000,000","219,522,496,000,000","120,275,933,000,000","175,231,153,000,000","14,239,592,000,000","13,229,908,000,000","13,229,908,000,000"
2,01170962,CFS,"2,491,420,979","6,390,292,498","8,881,713,477","4,005,509,638","4,876,203,839","4,574,221,304","798,079,282","600,145,982","600,145,982"
3,01139266,CFS,"4,737,704,248","359,005,973","5,096,710,221","3,825,329,005","1,271,381,216","2,693,371,318","103,270,506","91,781,317","91,781,317"
4,01107665,CFS,"1,539,117,621","1,066,578,097","2,605,695,718","171,083,285","2,434,612,433","518,897,047","99,577,615","44,846,555","44,846,555"

In [24]:
vv_df.head()

,corp_code,fs_div,유동자산,비유동자산,자산총계,부채총계,자본총계,매출액,영업이익,당기순이익,당기순이익(손실)
0,00126380,CFS,"227,062,266,000,000","287,469,682,000,000","514,531,948,000,000","112,339,878,000,000","402,192,070,000,000","300,870,903,000,000","32,725,961,000,000","34,451,351,000,000","34,451,351,000,000"
1,00164742,CFS,"115,764,287,000,000","224,034,142,000,000","339,798,429,000,000","219,522,496,000,000","120,275,933,000,000","175,231,153,000,000","14,239,592,000,000","13,229,908,000,000","13,229,908,000,000"
2,01170962,CFS,"2,491,420,979","6,390,292,498","8,881,713,477","4,005,509,638","4,876,203,839","4,574,221,304","798,079,282","600,145,982","600,145,982"
3,01139266,CFS,"4,737,704,248","359,005,973","5,096,710,221","3,825,329,005","1,271,381,216","2,693,371,318","103,270,506","91,781,317","91,781,317"
4,01107665,CFS,"1,539,117,621","1,066,578,097","2,605,695,718","171,083,285","2,434,612,433","518,897,047","99,577,615","44,846,555","44,846,555"